version: "3.6"
services:
  node:
    container_name: pwa_blog_tp
    image: "node:alpine"
    working_dir: /home/app
    command:
      - /bin/sh
      - "-c"
      - "npm install && npm start"
    ports:
      - "3000:8080"
    volumes:
      - "./src:/home/app"
